In [1]:
import numpy as np

In [5]:
l = [1,2,3,4,5]

In [6]:
array = np.array(l)

In [7]:
type(array)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [10]:
a = [2,3,4]

In [11]:
np.asanyarray(a)

array([2, 3, 4])

In [12]:
b = np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4, 5]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [15]:
a = np.array(l)

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
c = a

In [18]:
c

array([1, 2, 3, 4, 5])

In [19]:
a

array([1, 2, 3, 4, 5])

In [20]:
c[0] = 100

In [21]:
c

array([100,   2,   3,   4,   5])

In [22]:
a

array([100,   2,   3,   4,   5])

In [23]:
np.fromfunction(lambda i, j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
iterable = (i*i for i in range(5))

In [25]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [26]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [27]:
list1 = [2,3,4,5,6]

In [28]:
arr = np.array(list1)

In [29]:
arr.ndim

1

In [30]:
arr2 = np.array([[1,2,3,4],[2,3,4,5]])

In [31]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [32]:
arr2.ndim

2

In [33]:
arr2.size

8

In [34]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [35]:
arr2.shape

(2, 4)

In [38]:
arr2.dtype

dtype('int64')

In [39]:
ar22 = np.array([(1.4,54,89),(23,65,98)])

In [40]:
ar22

array([[ 1.4, 54. , 89. ],
       [23. , 65. , 98. ]])

In [42]:
ar22.dtype

dtype('float64')

In [47]:
list(range(5))

[0, 1, 2, 3, 4]

In [50]:
list(np.arange(2.3,6))

[2.3, 3.3, 4.3, 5.3]

In [52]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [56]:
ar4 = np.zeros((3,4,2,5))

In [57]:
ar4.ndim

4

In [61]:
one = np.ones((2,3,2))

In [62]:
one.ndim

3

In [63]:
one  + 7

array([[[8., 8.],
        [8., 8.],
        [8., 8.]],

       [[8., 8.],
        [8., 8.],
        [8., 8.]]])

In [64]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [65]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [66]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [67]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [75]:
arr = np.random.randn(3,4)

In [2]:
import pandas as pd

In [77]:
pd.DataFrame(arr)

0         1         2         3
0  0.384780  0.887887 -0.029940 -0.088863
1 -0.164030  1.409364 -0.636096  0.927509
2  0.438456 -0.696678  1.426248 -2.086383

In [78]:
np.random.randn(3,4)

array([[ 1.41847473, -1.21625293,  1.46115974, -0.00328907],
       [ 2.2453039 ,  1.63512125, -1.47419266,  1.36667472],
       [ 0.75299773,  0.24021213,  0.8679592 , -0.37071577]])

In [80]:
np.random.rand(3,4)

array([[0.36376118, 0.9392053 , 0.09560532, 0.29911463],
       [0.75316987, 0.84874131, 0.85780999, 0.31244419],
       [0.08311727, 0.33993215, 0.34892258, 0.46873566]])

In [82]:
pd.DataFrame(np.random.randint(1,110,(300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0    109   30   36   91   73   93    4   36   49   44  ...   59   11   88   
1    103   34   55   29    6    9   90   83   77   93  ...   71   78   92   
2     55   18   88   81   72  105   62   63    8  104  ...   47  108   43   
3     87   72   69  105   10   75   94   68   87   93  ...   32   59   89   
4     83    1   35    4   96   32   14  102   65   37  ...   83   90   12   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   33   49    7  107   39   34    9   32   17  107  ...   22   50   40   
296  101    4    7   21   74   50   80   32  102   22  ...   54   69   87   
297   25   90   49   73   54   76   35   88   90   10  ...   98   27   71   
298   88  103   53   37   47   60   81    5    7   86  ...   90   53   82   
299  104   68   60   66   75   70   17   71   74   14  ...   10   18  101   

     393  394  395  396  397  398  399  
0     32  104   65   94   58   35   21  
1     55   75   92   86   68   44   94  
2     15   64   41   13   92   88   36  
3     73   86   59   40   55   24   54  
4      7   21  108    7    2   98   10  
..   ...  ...  ...  ...  ...  ...  ...  
295   18   96   51   63   61   79   38  
296    9   71   20   38    6   38    1  
297   87   43   12   59   55   41   84  
298   37   40   67   48    7   26   83  
299   27   87   67  107  104   62   23  

[300 rows x 400 columns]

In [3]:
pd.DataFrame(np.random.randint(1,110, (300,400))).to_csv('t.csv')

In [4]:
z = np.random.rand(3,4)

In [5]:
z

array([[0.64659252, 0.49118344, 0.20135807, 0.7116204 ],
       [0.35085474, 0.46247338, 0.9279701 , 0.68098166],
       [0.64957704, 0.09120515, 0.19866481, 0.57537016]])

In [7]:
arrr1 = z.reshape(6,2)

In [11]:
arrr1

array([[0.64659252, 0.49118344],
       [0.20135807, 0.7116204 ],
       [0.35085474, 0.46247338],
       [0.9279701 , 0.68098166],
       [0.64957704, 0.09120515],
       [0.19866481, 0.57537016]])

In [24]:
arrr1[1][1]

0.7116203960980757

In [25]:
arrr1[2:5,[1]]

array([[0.46247338],
       [0.68098166],
       [0.09120515]])

In [32]:
a = np.random.randint(1,100, (5,5))

In [36]:
a

array([[24,  3, 58, 97, 16],
       [67, 38, 91, 43, 10],
       [70, 93, 49, 61, 52],
       [80, 33, 83, 78,  1],
       [ 1, 67, 17, 59,  6]])

In [38]:
a[a>50]

array([58, 97, 67, 91, 70, 93, 61, 52, 80, 83, 78, 67, 59])

In [42]:
a[2:4, [1,2]]

array([[93, 49],
       [33, 83]])

In [46]:
a[0][0] = 5000

In [47]:
a

array([[5000,    3,   58,   97,   16],
       [  67,   38,   91,   43,   10],
       [  70,   93,   49,   61,   52],
       [  80,   33,   83,   78,    1],
       [   1,   67,   17,   59,    6]])

In [54]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [55]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [2, 1, 2]])

In [56]:
arr2

array([[1, 2, 1],
       [1, 2, 2],
       [2, 2, 1]])

In [57]:
arr1 + arr2

array([[3, 3, 3],
       [3, 4, 4],
       [4, 3, 3]])

In [58]:
arr1 - arr2

array([[ 1, -1,  1],
       [ 1,  0,  0],
       [ 0, -1,  1]])

In [59]:
arr1/arr2

array([[2. , 0.5, 2. ],
       [2. , 1. , 1. ],
       [1. , 0.5, 2. ]])

In [60]:
arr1 * arr2

array([[2, 2, 2],
       [2, 4, 4],
       [4, 2, 2]])

In [61]:
arr1@arr2

array([[ 7, 10,  6],
       [ 8, 12,  8],
       [ 7, 10,  6]])

In [62]:
arr1**2

array([[4, 1, 4],
       [4, 4, 4],
       [4, 1, 4]])

In [64]:
arr = np.zeros((4,4))

In [65]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
row = np.array([1,2,3,4])

In [73]:
row

array([1, 2, 3, 4])

In [74]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [75]:
row.T

array([1, 2, 3, 4])

In [76]:
arr.T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
col = np.array([[1,2,3,4]])

In [78]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [79]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
arr1 = np.random.randint(1,4 , (3,4))

In [86]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081, 1.41421356],
       [1.        , 1.        , 1.41421356, 1.41421356]])

In [87]:
np.exp(arr1)

array([[ 2.71828183,  2.71828183,  7.3890561 , 20.08553692],
       [20.08553692, 20.08553692, 20.08553692,  7.3890561 ],
       [ 2.71828183,  2.71828183,  7.3890561 ,  7.3890561 ]])

In [93]:
np.log10(arr1)

array([[0.        , 0.        , 0.30103   , 0.47712125],
       [0.47712125, 0.47712125, 0.47712125, 0.30103   ],
       [0.        , 0.        , 0.30103   , 0.30103   ]])

In [94]:
# Array Manipulation

In [168]:
import numpy as np

In [96]:
arr = np.random.randint(1,10, (3,4))

In [97]:
arr

array([[8, 8, 7, 1],
       [4, 9, 1, 9],
       [4, 7, 7, 8]])

In [99]:
arr.reshape(2,6)

array([[8, 8, 7, 1, 4, 9],
       [1, 9, 4, 7, 7, 8]])

In [100]:
arr.T

array([[8, 4, 4],
       [8, 9, 7],
       [7, 1, 7],
       [1, 9, 8]])

In [101]:
arr.flatten()

array([8, 8, 7, 1, 4, 9, 1, 9, 4, 7, 7, 8])

In [102]:
arr1 = np.array([1,2,3,4,5])

In [103]:
arr1.ndim

1

In [109]:
arr1 = np.expand_dims(arr1, axis = 0)

In [110]:
arr1

array([[[[1],
         [2],
         [3],
         [4],
         [5]]]])

In [111]:
np.squeeze(arr)

array([[8, 8, 7, 1],
       [4, 9, 1, 9],
       [4, 7, 7, 8]])

In [112]:
data = np.array([[1],[2],[3]])

In [113]:
data

array([[1],
       [2],
       [3]])

In [115]:
np.squeeze(data)

array([1, 2, 3])

In [116]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [119]:
np.roll(arr1,shift = 2)

array([[[[4],
         [5],
         [1],
         [2],
         [3]]]])

In [ ]:
np.diag(arr1)

In [121]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [122]:
arr1

array([[5, 7, 8, 8],
       [9, 5, 1, 6],
       [8, 5, 5, 8]])

In [123]:
arr2


array([[2, 1, 5, 5],
       [6, 3, 5, 9],
       [6, 3, 7, 3]])

In [124]:
arr1 + arr2 

array([[ 7,  8, 13, 13],
       [15,  8,  6, 15],
       [14,  8, 12, 11]])

In [125]:
arr1 * arr2

array([[10,  7, 40, 40],
       [54, 15,  5, 54],
       [48, 15, 35, 24]])

In [126]:
arr1/arr2

array([[2.5       , 7.        , 1.6       , 1.6       ],
       [1.5       , 1.66666667, 0.2       , 0.66666667],
       [1.33333333, 1.66666667, 0.71428571, 2.66666667]])

In [127]:
arr1%arr2

array([[1, 0, 3, 3],
       [3, 2, 1, 6],
       [2, 2, 5, 2]])

In [128]:
arr1 ** arr2

array([[      25,        7,    32768,    32768],
       [  531441,      125,        1, 10077696],
       [  262144,      125,    78125,      512]])

In [129]:
arr1 & arr2

array([[0, 1, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 5, 0]])

In [130]:
arr1

array([[5, 7, 8, 8],
       [9, 5, 1, 6],
       [8, 5, 5, 8]])

In [131]:
arr2

array([[2, 1, 5, 5],
       [6, 3, 5, 9],
       [6, 3, 7, 3]])

In [132]:
-arr1

array([[-5, -7, -8, -8],
       [-9, -5, -1, -6],
       [-8, -5, -5, -8]])

In [133]:
-arr2

array([[-2, -1, -5, -5],
       [-6, -3, -5, -9],
       [-6, -3, -7, -3]])

In [135]:
arr1 | arr2

array([[ 7,  7, 13, 13],
       [15,  7,  5, 15],
       [14,  7,  7, 11]])

In [136]:
 arr1 > arr2

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True, False,  True]])

In [137]:
arr1 < arr2

array([[False, False, False, False],
       [False, False,  True,  True],
       [False, False,  True, False]])

In [138]:
arr1 >= arr2

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True, False,  True]])

In [139]:
arr1 <= arr2

array([[False, False, False, False],
       [False, False,  True,  True],
       [False, False,  True, False]])

In [140]:
# string function

In [142]:
arr = np.array(['nikhil','lokare'])

In [143]:
np.char.upper(arr)

array(['NIKHIL', 'LOKARE'], dtype='<U6')

In [145]:
np.char.title(arr)

array(['Nikhil', 'Lokare'], dtype='<U6')

In [147]:
np.char.capitalize(arr)

array(['Nikhil', 'Lokare'], dtype='<U6')

In [148]:
# mathematical functions

In [150]:
arr1

array([[5, 7, 8, 8],
       [9, 5, 1, 6],
       [8, 5, 5, 8]])

In [152]:
np.sin(arr1)

array([[-0.95892427,  0.6569866 ,  0.98935825,  0.98935825],
       [ 0.41211849, -0.95892427,  0.84147098, -0.2794155 ],
       [ 0.98935825, -0.95892427, -0.95892427,  0.98935825]])

In [153]:
np.cos(arr1)

array([[ 0.28366219,  0.75390225, -0.14550003, -0.14550003],
       [-0.91113026,  0.28366219,  0.54030231,  0.96017029],
       [-0.14550003,  0.28366219,  0.28366219, -0.14550003]])

In [154]:
np.tan(arr1)

array([[-3.38051501,  0.87144798, -6.79971146, -6.79971146],
       [-0.45231566, -3.38051501,  1.55740772, -0.29100619],
       [-6.79971146, -3.38051501, -3.38051501, -6.79971146]])

In [158]:
np.log10(arr1)

array([[0.69897   , 0.84509804, 0.90308999, 0.90308999],
       [0.95424251, 0.69897   , 0.        , 0.77815125],
       [0.90308999, 0.69897   , 0.69897   , 0.90308999]])

In [159]:
np.exp(arr1)

array([[1.48413159e+02, 1.09663316e+03, 2.98095799e+03, 2.98095799e+03],
       [8.10308393e+03, 1.48413159e+02, 2.71828183e+00, 4.03428793e+02],
       [2.98095799e+03, 1.48413159e+02, 1.48413159e+02, 2.98095799e+03]])

In [161]:
np.sqrt(arr1*2)

array([[3.16227766, 3.74165739, 4.        , 4.        ],
       [4.24264069, 3.16227766, 1.41421356, 3.46410162],
       [4.        , 3.16227766, 3.16227766, 4.        ]])

In [163]:
np.power(arr1,2)

array([[25, 49, 64, 64],
       [81, 25,  1, 36],
       [64, 25, 25, 64]])

In [164]:
np.mean(arr1)

6.25

In [165]:
np.median(arr1)

6.5

In [170]:
np.std(arr1)

2.1262251370288454

In [173]:
np.var(arr1)

4.520833333333333

In [174]:
np.min(arr1)

1

In [175]:
np.max(arr1)

9

In [176]:
# sort,search,counting functions

In [177]:
arr = np.array([5,4,6,7,9,3,2,1])

In [179]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [182]:
np.searchsorted(arr, 55)

8

In [184]:
ar = np.array([33,66,88,2324,8985,4,99])

In [188]:
np.count_nonzero(ar)

7

In [190]:
ar

array([  33,   66,   88, 2324, 8985,    4,   99])

In [192]:
np.where(ar > 6)

(array([0, 1, 2, 3, 4, 6]),)

In [195]:
np.extract(arr > 6 ,arr)

array([7, 9])

In [196]:
# byte swapping

In [197]:
arr.byteswap()

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680, 432345564227567616,
       504403158265495552, 648518346341351424])

In [198]:
# copies and views

In [199]:
arr

array([1, 2, 3, 4, 5, 6, 7, 9])

In [200]:
a = np.copy(arr)

In [201]:
a

array([1, 2, 3, 4, 5, 6, 7, 9])

In [202]:
b = arr.view()

In [203]:
b

array([1, 2, 3, 4, 5, 6, 7, 9])

In [204]:
b[0] = 8

In [205]:
arr

array([8, 2, 3, 4, 5, 6, 7, 9])

In [206]:
b = arr

In [207]:
b

array([8, 2, 3, 4, 5, 6, 7, 9])

In [208]:
# maxtrix libray

In [209]:
import numpy.matlib as nm

In [210]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [212]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [213]:
# linera algebra

In [214]:
arr1 = np.random.randint([[2,3],[4,5]])

In [215]:
arr2 = np.random.randint([[5,3],[2,5]])

In [216]:
arr1

array([[1, 1],
       [3, 0]])

In [217]:
arr2

array([[0, 1],
       [0, 4]])

In [218]:
arr1 @ arr2

array([[0, 5],
       [0, 3]])

In [219]:
arr1 * arr2

array([[0, 1],
       [0, 0]])

In [220]:
arr1 + arr2

array([[1, 2],
       [3, 4]])